@startuml
hide circle

entity "Cart Item" as ca {
  Id : ID
  --
  Product2Id : ID
}

entity "Product2" as p {
  Id : ID 
  --
  TaxPolicyId : ID 
}

entity "Tax Policy" as tp {
  Id : ID
  --
  DefaultTaxTreatmentId : ID
}

entity "Tax Treatment" as tt {
  Id : ID
  --
  TaxCode : Text
}

entity "Tax Rate" as tr {
  TaxCode : Text
  --
  Rate : Number
  GeoCountryId : ID
}

entity "Geo Country" as gc {
  Id : Text
  --
  Rate : Number
}

ca ||--|| p
p ||--|| tp
tp ||--|| tt
tt -- tr
tr }o--|| gc

@enduml